apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  # replicas - no of pods of a particular image
  replicas: 1

  # selector - find all the pods with label app: posts and manage them
  selector:
    matchLabels:
      app: posts

  # template specifies the config of the pod we want to create
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: srisaiomkar/posts
